
pipeline:
  rsync-step1:
    image: drillster/drone-rsync
    hosts:
      - 35.189.191.155
    user: joshgu
    secrets: [ rsync_key ]
    recursive: true
    source: ./
    target: ~/www/
    delete: true

