
pipeline:
  build:
    image: golang
    commands:
      - go build
      - echo joshgu1009
      - echo rsync_key
  rsync-step1:
    image: drillster/drone-rsync
    hosts:
      - 35.189.191.155
    secrets: [ joshgu1009, rsync_key ]
    recursive: true
    source: ./
    target: ~/www/
    delete: true

