pipeline:
  build:
    image: golang
    commands:
      - go build
      - echo rsync_user
      - echo rsync_key
  rsync-step1:
    image: drillster/drone-rsync
    hosts:
      - 35.189.191.155
    environment:
      USERNAME:
        from_secret: user
      PASSWORD:
        from_secret: key
    recursive: true
    source: ./
    target: ~/www/${DRONE_REPO_NAME}
    delete: true

